# Generated by Django 5.1.3 on 2024-11-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("base_experience", models.IntegerField(default=0)),
                ("height", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                ("is_default", models.BooleanField(default=False)),
                ("order", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
