# Generated by Django 5.1.3 on 2024-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="sprites",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
