# Generated by Django 5.1.3 on 2024-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="test_field",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Test Field"
            ),
        ),
    ]
