# Generated by Django 5.1.3 on 2024-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0002_pokemon_species_pokemon_sprites"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "pokemon",
                    models.ManyToManyField(related_name="types", to="pokemon.pokemon"),
                ),
            ],
        ),
    ]
