# Generated by Django 5.1.3 on 2024-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0002_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
