# Generated by Django 5.1.3 on 2024-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pokemon", "0003_pokemontype")]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="waka_waka",
            field=models.CharField(default="WAKA_WAKA", max_length=255),
        ),
    ]
