# Generated by Django 5.1.3 on 2024-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0003_pokemontype"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemontype",
            name="new_field",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
