# Generated by Django 5.1.3 on 2024-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0004_pokemon_waka_waka"),
        ("pokemon", "0004_pokemontype_new_field"),
    ]

    operations = []
